config/routes.rb
Rails.application.routes.draw do
  root 'menu#index'
  get 'checkout', to: 'checkouts#show'
  get 'order/success', to: 'checkouts#success'
  get 'order/cancel', to: 'checkouts#cancel'
  resources :order_positions
  resources :admins do
    collection do
      put :update
    end
  end
  resources :requests
  get 'cart', to: 'cart#show'
  post 'cart/approve', to: 'cart#approve'
  devise_for :users, controllers: { registrations: 'client_registrations', omniauth_callbacks: 'users/omniauth_callbacks', passwords: 'passwords', sessions: 'sessions' }, class_name: 'User'
  devise_for :restaurants,
    class_name: 'User',
    only: [],
    controllers: { registrations: 'restaurants' }

  devise_scope :restaurant do
    get   "/restaurants/new", to: "restaurants#new", as: :new_restaurant
    post  "/restaurants",    to: "restaurants#create", as: :restaurants
    get  "/restaurants/destroy",    to: "restaurants#destroy", as: :destroy_restaurant_session
  end

  resources :restaurant, only: %i[index show destroy] do
    get :products
  end
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/403', to: 'errors#not_authorized', via: :all
  resources :phone_verifications, only: %i[new create] do
    collection do
      get 'challenge'
      post 'verify'
      get 'success'
    end
  end
  resources :after_signup
  resources :restaurant_orders, only: %i[index] do
    collection do
      post :update
    end
  end
  get '/search', to: 'pages#search', as: 'search_page'
  resources :restaurant_steps
  resources :user do
    resources :products do
      resources :comments, only: %i[create destroy]
    end
    resources :orders, only: %i[index]
    collection do
      get 'profile'
      get 'dishes'
    end
    member do
      get :edit_phone_number
      patch :update_phone_number
      put :update_phone_number
    end
  end
  mount ActionCable.server => '/cable'
end

app/controllers/restaurant_controller.rb
# frozen_string_literal: false

# Pages for restaurant and their products
class RestaurantController < ApplicationController
  include Constants
  before_action :init_cart
  def index
    @restaurants = admin(current_user) ? User.restaurant : User.restaurant.confirmed
    @pagy, @list_of_restaurants = pagy(@restaurants.includes(avatar_attachment: :blob), items: ITEMS)
  end

  def show
    @restaurant = User.find(params[:id])
  end

  def products
    @products = User.find(params[:restaurant_id]).products.includes(product_picture_attachment: :blob)
  end

  def destroy
    if User.find(params[:id]).destroy
      redirect_back fallback_location: root_path
      flash[:notice] = 'Restaurant was successfully destroyed.'
    else
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/restaurants_controller.rb
# frozen_string_literal: false

# Responsible for registration through devise
class RestaurantsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(_resource)
    restaurant_steps_path
  end

  def sign_up_params
    params.require(:user).permit(
      :phone_number,
      :password,
      :password_confirmation
    ).merge(user_type: 2, create_stage: 0)
  end
end

app/views/restaurant/index.html.slim
body
  section.jumbotron.text-center[style="margin: 0;"]
    - unless @restaurants.nil?
      .album.py-5.bg-light
        section.text-center.h1 #{t 'menu_page.restaurants'}
        .container
          .row
            - @list_of_restaurants.each do |user|
              .col-md-4
                .card.mb-4.box-shadow
                  img.card-img-top[data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;
          text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="#{url_for(user.avatar)}" data-holder-rendered="true"]
                  .card-body
                    h3.card-text
                      = user.name
                    h6.card-text
                      = user.address
                    .d-flex.justify-content-between.align-items-center
                      .btn-group
                        = button_to (t 'menu_page.view'), restaurant_path(user), method: :get, class: 'btn btn-primary'
                        - if admin(current_user)
                          = button_to 'Delete', restaurant_path(user), class: 'btn btn-danger', method: :delete
                        - unless user.confirmed
                          = button_to 'Confirm', { controller: 'admins', action: 'update', restaurant_id: user}, class: 'btn btn-success', method: :put
                        small.text-muted
                          = user.phone_number unless admin(current_user)
          = pagy_bootstrap_nav(@pagy).html_safe

app/views/restaurant/products.html.slim
body[style="background-color: #e9ecef"]
  section.jumbotron.text-center[style="margin: 0;"]
    .album.py-5.bg-light
        section.text-center.h1 #{t 'menu_page.restaurant_products' }
        .container
          .row
            - @products.each do |product|
              - next unless product.approved unless admin(current_user)
              .col-md-4
                .card.mb-4.box-shadow
                    img.card-img-top[data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;
  text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;"
  src="#{url_for(product.product_picture)}"   data-holder-rendered="true"]
                    .card-body
                      h3.card-text
                        = product.name
                      h6.card-text
                        = product.category
                      p.card-text
                        = product.description
                      = render 'order_positions/form', order_positions: @order_positions, product: product unless client(current_user)
                      .d-flex.justify-content-between.align-items-center
                        - unless product.approved
                          = button_to 'Confirm', { controller: 'admins', action: 'update', product_id: product}, class: 'btn btn-success', method: :put
                        small.text-muted
                          = product.price

app/views/restaurant/show.html.slim
body
.container.p-0[style="height: 100vh;"]
  br
  .row
    .col-md-7.col-xl-8
      .tab-content
        #account.tab-pane.fade.show.active[role="tabpanel"]
          .card
            .card-header
              .card-actions.float-right
              h5.card-title.mb-0
                = t 'menu_page.rest_info'
            .card-body
              form
                .row
                  .col-md-8
                    .form-group
                      image src="#{url_for(@restaurant.avatar)}"
                    .form-group
                      label
                        = t 'profile.name'
                      = @restaurant.name
                    .form-group
                      label
                        = t 'profile.email'
                      = @restaurant.email
                    .form-group
                      label
                        = t 'profile.city'
                        = @restaurant.address
                    .form-group
                      label
                        = t 'profile.phone'
                      = @restaurant.phone_number
                      br
                      = link_to (t 'profile.dishes'), restaurant_products_path(@restaurant), id: @restaurant