config/routes.rb
Rails.application.routes.draw do
  root 'menu#index'
  get 'checkout', to: 'checkouts#show'
  get 'order/success', to: 'checkouts#success'
  get 'order/cancel', to: 'checkouts#cancel'
  resources :order_positions
  resources :admins do
    collection do
      put :update
    end
  end
  resources :requests
  get 'cart', to: 'cart#show'
  post 'cart/approve', to: 'cart#approve'
  devise_for :users, controllers: { registrations: 'client_registrations', omniauth_callbacks: 'users/omniauth_callbacks', passwords: 'passwords', sessions: 'sessions' }, class_name: 'User'
  devise_for :restaurants,
    class_name: 'User',
    only: [],
    controllers: { registrations: 'restaurants' }

  devise_scope :restaurant do
    get   "/restaurants/new", to: "restaurants#new", as: :new_restaurant
    post  "/restaurants",    to: "restaurants#create", as: :restaurants
    get  "/restaurants/destroy",    to: "restaurants#destroy", as: :destroy_restaurant_session
  end

  resources :restaurant, only: %i[index show destroy] do
    get :products
  end
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/403', to: 'errors#not_authorized', via: :all
  resources :phone_verifications, only: %i[new create] do
    collection do
      get 'challenge'
      post 'verify'
      get 'success'
    end
  end
  resources :after_signup
  resources :restaurant_orders, only: %i[index] do
    collection do
      post :update
    end
  end
  get '/search', to: 'pages#search', as: 'search_page'
  resources :restaurant_steps
  resources :user do
    resources :products do
      resources :comments, only: %i[create destroy]
    end
    resources :orders, only: %i[index]
    collection do
      get 'profile'
      get 'dishes'
    end
    member do
      get :edit_phone_number
      patch :update_phone_number
      put :update_phone_number
    end
  end
  mount ActionCable.server => '/cable'
end

app/models/user.rb
# frozen_string_literal: false

# Model which describes users
class User < ApplicationRecord
  pay_customer
  before_validation :normalize_phone
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[google_oauth2 twitter]

  validates_with UserValidator
  validates :phone_number, uniqueness: true, phone: { possible: true, types: :mobile, countries: :by }
  validates_uniqueness_of :email, if: :email
  has_many :restaurant_orders, dependent: :delete_all
  has_many :products, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :avatar
  accepts_nested_attributes_for :comments
  scope :confirmed, -> { where(confirmed: true) }
  validates :avatar, attached: true, content_type: %i[png jpg jpeg], if: -> { create_stage == 2 }
  accepts_nested_attributes_for :products, reject_if: :all_blank, allow_destroy: true
  enum user_type: { admin: 0, client: 1, restaurant: 2 }

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_create do |user|
      user.email = auth.info.email
      user.phone_number = nil
      user.user_type = 1
      user.create_stage = 0
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
    end
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if conditions[:phone_number]
      find_by_phone_number(conditions[:phone_number])
    elsif conditions[:email]
      find_by_email(conditions[:email])
    elsif conditions.key?(:reset_password_token)
      find_by_reset_password_token(conditions[:reset_password_token])
    end
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end

  def all_contact_info_filled?
    !(name && email && city).nil?
  end

  def address
    "#{city}, #{street} #{house_number}"
  end

  def restaurant_products
    products.includes([:restaurant]).includes(product_picture_attachment: :blob)
  end

  private

  def normalize_phone
    self.phone_number = Phonelib.parse(phone_number).full_e164.presence
  end
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: false

module Api
  module V1
    class UsersController < ApplicationController
      def index
        users = User.all

        render json: UserSerializer.new(users).serializable_hash.to_json
      end
    end
  end
end

app/controllers/user_controller.rb
# frozen_string_literal: false

# Controller for client profile page
class UserController < ApplicationController
  before_action :authenticate_user!

  def phone_number; end

  def profile
    return redirect_to edit_phone_number_user_path(current_user) unless current_user.phone_number
    return redirect_to edit_user_path(current_user) unless current_user.all_contact_info_filled?
  end

  def edit
    redirect_to edit_phone_number_user_path(current_user) if current_user.phone_number.blank?
  end

  def edit_phone_number; end

  def update
    if current_user.update(user_params.merge(create_stage: 1))
      current_user.update(confirmed: false) if current_user.restaurant?
      current_user.confirmed || !current_user.client? ? (redirect_to root_path) : (redirect_to after_signup_index_path)
    else
      respond_to do |format|
        format.html { render action: :edit }
      end
    end
  end

  def update_phone_number
    respond_to do |format|
      if current_user.update(user_params)
        format.html { redirect_to after_signup_index_path }
      else
        format.html { render action: :edit }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :city,
      :phone_number
    )
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: false

module Users
  # Controller for omniauth to get data from outside services
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
      @user = User.from_omniauth(request.env['omniauth.auth'])
      if @user.save(validate: false)
        sign_and_redirect
        set_flash_message(:notice, :success, kind: 'Google') if is_navigational_format?
      else
        set_flash_message(:notice, :fail, kind: 'Google') if is_navigational_format?
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra)
        redirect_to root_path
      end
    end

    def twitter
      @user = User.from_omniauth(request.env['omniauth.auth'])
      if @user.save(validate: false)
        sign_and_redirect
        set_flash_message(:notice, :success, kind: 'Twitter') if is_navigational_format?
      else
        set_flash_message(:notice, :fail, kind: 'Google') if is_navigational_format?
        session['devise.twitter_data'] = request.env['omniauth.auth'].except(:extra)
        redirect_to root_path
      end
    end

    def failure
      redirect_to root_path
    end

    private

    def sign_and_redirect
      sign_in(@user)
      redirect_to current_user.phone_number ? root_path : edit_phone_number_user_path(current_user)
    end
  end
end

app/views/user/_form.html.slim
.container.p-0[style="height: 100vh;"]
  h1.h3.mb-3
    = t 'profile.settings'
  .row
    .col-md-5.col-xl-4
      = render 'user/panel'
    .col-md-7.col-xl-8
      .tab-content
        #account.tab-pane.fade.show.active[role="tabpanel"]
          .card
            .card-header
              .card-actions.float-right
              h5.card-title.mb-0
                = t 'profile.info_change'
          = form_with(model: current_user) do |f|
            - if current_user.errors.any?
              ul
                - current_user.errors.each do |error|
                  li
                    = error.full_message
            .field
              = f.label :name
              br
              = f.text_field :name, autofocus: true
            .field
              = f.label :email
              br
              = f.email_field :email, autofocus: true, autocomplete: 'email'
            .field
              = f.label :city
              br
              = f.text_field :city, autofocus: true, autocomplete: 'city'
            .actions
            br
              = f.submit (t 'devise.registrations.edit.update')

app/views/user/_panel.html.slim
.card
  .card-header
    h5.card-title.mb-0
      = t 'profile.profile_settings'
  .list-group.list-group-flush[role="tablist"]
    a.list-group-item.list-group-item-action[data-toggle="list" href=profile_user_index_path role="tab"]
      = t 'profile.my_page'
    - if current_user.admin?
      a.list-group-item.list-group-item-action[data-toggle="list" href=requests_path role="tab"]
        = t 'profile.registration_request'
    - if current_user.restaurant?
      a.list-group-item.list-group-item-action[data-toggle="list" href=dishes_user_index_path role="tab"]
        = t 'profile.dishes'
      a.list-group-item.list-group-item-action[data-toggle="list" href=new_user_product_path(current_user) role="tab"]
        = t 'profile.insert_dishes'
      a.list-group-item.list-group-item-action[data-toggle="list" href=restaurant_orders_path role="tab"]
        = t 'profile.restaurant_orders'
    a.list-group-item.list-group-item-action[data-toggle="list" href=edit_user_path(current_user) role="tab"]
      = t 'profile.info_change'
    a.list-group-item.list-group-item-action[data-toggle="list" href=edit_user_registration_path role="tab"]
      = t 'profile.password_change'
    - if current_user.client?
      a.list-group-item.list-group-item-action[data-toggle="list" href=after_signup_index_path role="tab"]
        = t 'profile.verify'
      a.list-group-item.list-group-item-action[data-toggle="list" href=user_orders_path(current_user) role="tab"]
        = t 'profile.order_history'

app/views/user/dishes.html.slim
.container.p-0
  h1.h3.mb-3
    = t 'profile.settings'
  .row
    .col-md-5.col-xl-4
      = render 'user/panel'
    .col-md-7.col-xl-8
      .tab-content
        #account.tab-pane.fade.show.active[role="tabpanel"]
          .card
            .card-header
              .card-actions.float-right
              h5.card-title.mb-0
                | Dishes
            .container
              .row
                - current_user.restaurant_products.each do |product|
                  .col-md-4
                    .card.mb-4.box-shadow
                      img.card-img-top[data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;
  text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;"
  src="#{url_for(product.product_picture)}"   data-holder-rendered="true"]
                      .card-body
                        h3.card-text
                          = product.name
                        h6.card-text
                          = product.category
                        p.card-text
                          = product.description
                        .d-flex.justify-content-between.align-items-center
                          small.text-muted
                            = product.price
                        = link_to 'Edit', edit_user_product_path(id: product, user_id: product.restaurant)
                        br
                        = link_to 'Delete', [product.restaurant, product], method: :delete

app/views/user/edit.html.slim
= render 'form'

app/views/user/edit_phone_number.html.slim
.container.p-0[style="height: 100vh;"]
  h1.h3.mb-3
    = t 'profile.settings'
  .row
    .col-md-5.col-xl-4
      = render 'user/panel'
    .col-md-7.col-xl-8
      .tab-content
        #account.tab-pane.fade.show.active[role="tabpanel"]
          .card
            .card-header
              .card-actions.float-right
              h5.card-title.mb-0
                | Profile information change
          = form_with(model: current_user, url: {action: 'update_phone_number'}) do |f|
            - if current_user.errors.any?
              ul
                - current_user.errors.each do |error|
                  li
                    = error.full_message
            - if current_user.phone_number.nil? || !(current_user.errors[:phone_number].blank?)
              h1 Enter your phone number
              .field
                = f.label :phone_number
                br
                = f.telephone_field :phone_number, autofocus: true, autocomplete: 'phone_number'
              .actions
                br
                = f.submit (t 'devise.registrations.edit.update')

app/views/user/profile.html.slim
body
.container.p-0[style="height: 100vh;"]
  h1.h3.mb-3
    = t 'profile.my_page'
  .row
    .col-md-5.col-xl-4
      = render 'user/panel'
    .col-md-7.col-xl-8
      .tab-content
        #account.tab-pane.fade.show.active[role="tabpanel"]
          .card
            .card-header
              .card-actions.float-right
              h5.card-title.mb-0
                = t 'profile.info'
            .card-body
              form
                .row
                  .col-md-8
                    .form-group
                      label
                        = t 'profile.name'
                      = current_user.name
                    .form-group
                      label
                        = t 'profile.email'
                      = current_user.email
                    .form-group
                      label
                      - if current_user.restaurant?
                        = t 'profile.address'
                        = current_user.address
                      - else
                        | City:
                        = current_user.city
                    .form-group
                      label
                        = t 'profile.phone'
                      = current_user.phone_number
                    .form-group
                    - unless current_user.admin?
                      label
                        = t 'profile.account_status'
                      - if current_user.confirmed
                          = t 'profile.verified'
                      - else
                          = t 'profile.not_verified'