config/routes.rb
Rails.application.routes.draw do
  root 'menu#index'
  get 'checkout', to: 'checkouts#show'
  get 'order/success', to: 'checkouts#success'
  get 'order/cancel', to: 'checkouts#cancel'
  resources :order_positions
  resources :admins do
    collection do
      put :update
    end
  end
  resources :requests
  get 'cart', to: 'cart#show'
  post 'cart/approve', to: 'cart#approve'
  devise_for :users, controllers: { registrations: 'client_registrations', omniauth_callbacks: 'users/omniauth_callbacks', passwords: 'passwords', sessions: 'sessions' }, class_name: 'User'
  devise_for :restaurants,
    class_name: 'User',
    only: [],
    controllers: { registrations: 'restaurants' }

  devise_scope :restaurant do
    get   "/restaurants/new", to: "restaurants#new", as: :new_restaurant
    post  "/restaurants",    to: "restaurants#create", as: :restaurants
    get  "/restaurants/destroy",    to: "restaurants#destroy", as: :destroy_restaurant_session
  end

  resources :restaurant, only: %i[index show destroy] do
    get :products
  end
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
  match '/403', to: 'errors#not_authorized', via: :all
  resources :phone_verifications, only: %i[new create] do
    collection do
      get 'challenge'
      post 'verify'
      get 'success'
    end
  end
  resources :after_signup
  resources :restaurant_orders, only: %i[index] do
    collection do
      post :update
    end
  end
  get '/search', to: 'pages#search', as: 'search_page'
  resources :restaurant_steps
  resources :user do
    resources :products do
      resources :comments, only: %i[create destroy]
    end
    resources :orders, only: %i[index]
    collection do
      get 'profile'
      get 'dishes'
    end
    member do
      get :edit_phone_number
      patch :update_phone_number
      put :update_phone_number
    end
  end
  mount ActionCable.server => '/cable'
end

app/views/navigation/_nav.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  button.navbar-toggler[type='button' data-toggle='collapse' data-target='#navbarTogglerDemo03' aria-controls='navbarTogglerDemo03' aria-expanded='false' aria-label='Toggle navigation']
    span.navbar-toggler-icon

  a.navbar-brand[href=root_path]
    | Flunky
  #navbarTogglerDemo03.collapse.navbar-collapse
    ul.navbar-nav.mr-auto.mt-2.mt-lg-0
      li.nav-item.active
        a.nav-link[href=root_path]
          = t 'navigation.home'
      li.nav-item
        a.nav-link[href=profile_user_index_path]
          = t 'navigation.profile'
      li.nav-item
        a.nav-link[href=restaurant_index_path]
          = t 'navigation.restaurants'
      - unless client(current_user)
        li.nav-item
          a.nav-link[href=cart_path]
            = t 'navigation.cart'
      - unless user_signed_in?
        li.nav-item
          a.nav-link[href=new_request_path]
            = t 'navigation.request_registration'
      li.nav-item
        a.nav-link[href="#{root_path(locale: :en)}"]
          | English
      li.nav-item
        a.nav-link[href="#{root_path(locale: :be)}"]
          | Belarussian
    - if user_signed_in?
      span.navbar-nav
          a.nav-link[href=profile_user_index_path]
            = current_user.name
      span.navbar-nav
        a.nav-link[href=destroy_user_session_path]
          = t 'navigation.sign_out'
    - else
      span.navbar-nav
          a.nav-link[href=new_user_session_path]
            = t 'navigation.log_in'
      span.navbar-nav
          a.nav-link[href=new_user_registration_path]
            = t 'navigation.sign_up'
    end
    = form_tag(search_page_path, method: :get, class: 'navbar-form navbar-left') do
      .input-group
        = search_field_tag :query, params[:search], placeholder: "#{t 'navigation.search'}", class: "form-control"
        .input-group-btn
          = button_tag (t 'navigation.search'), class: 'btn btn-info glyphicon glyphicon-search', name: nil